# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: pt_br

pipeline:
- name: "SpacyNLP"
- name: "WhitespaceTokenizer"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
  # analyze: char
  # min_gram: 3
  # max_gram: 3
  similarity_type: cosine
  # random_seed: 0
- name: "CRFEntityExtractor"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
